= AsciiBook

AsciiBook is a tool for converting AsciiDoc documents into books. Book format includes single HTML, multiple HTML, pdf, epub, mobi and so on.

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'ascii_book'
----

And then execute:

[source,ruby]
----
bundle
----

Or install it yourself as:

[source,ruby]
----
gem install ascii_book
----

== Usage

Run the command to build book:

[source,ruby]
----
asciibook <index>.adoc
----

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake test` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org/[rubygems.org].

## Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/diguage/ascii_book. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the http://contributor-covenant.org/[Contributor Covenant] code of conduct.

## License

The gem is available as open source under the terms of the http://opensource.org/licenses/MIT[MIT License].

## Code of Conduct

Everyone interacting in the AsciiBook project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the https://github.com/diguage/ascii_book/blob/master/CODE_OF_CONDUCT.adoc[code of conduct].
